export const weatherImages = {
  'Partly cloudy': require('../assets/partlyCloudy.png'),
  'Partly Cloudy': require('../assets/partlyCloudy.png'),
  Cloudy: require('../assets/partlyCloudy.png'),
  'Cloudy ': require('../assets/partlyCloudy.png'),

  'Moderate rain': require('../assets/rain.png'),
  'Thunder rain': require('../assets/thunderRain.png'),
  'Night showers': require('../assets/nightShowers.png'),
  Sunny: require('../assets/sunshine.png'),
  'sunshine Shower': require('../assets/sunshineShowers.png'),
  'Light rain': require('../assets/lightrain.png'),
  'Moderate or heavy rain with thunder': require('../assets/moderateheavythunder.png'),
  'Light rain shower': require('../assets/lightrainshower.png'),
  Clear: require('../assets/clear.png'),
  'Clear ': require('../assets/clear.png'),
  Overcast: require('../assets/partlyCloudy.png'),
  Mist: require('../assets/mist.png'),
  'Patchy light rain with thunder': require('../assets/patchylightthunder.png'),
};
